version: "3.8"

services:
  options-tracker:
    build:
      context: https://github.com/Hilsre/options_tracker.git
    container_name: options-tracker
    ports:
      - "8501:8501"
    restart: unless-stopped
